import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from "next/link";
import Users from '../../components/users'
const USERS = [
    {
        name: 'Natalia',
        surename: 'Porczynska',
        age: '18',
        job: 'programmer',
        town: 'Poznan',
        mail: 'natalia.p@gmail.com'
    }   , {
        name: 'Ewa',
        surename: 'Kowalska',
        age: '23',
        job: 'tech lead',
        town: 'Poznan',
        mail: 'ewak@gmail.com'
    }
];

export default function UsersPage(props) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Users page!</a>
                </h1>

                <p className={styles.description}>
                    Get started by adding a user
                    <Link href="/newuser">
                        <code className={styles.code}>here</code>
                    </Link>
                </p>
                    <Users users={props.users}/>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}

export async function getStaticProps(){

    return {
        props: {
            users: USERS
        },
        revalidate: 10 // regenerate this page every 10 seconds on a server
    };
}
